/// Flutter icons JumaIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JumaIcons
///      fonts:
///       - asset: fonts/JumaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class JumaIcons {
  JumaIcons._();

  static const _kFontFam = 'JumaIcons';
  static const _kFontPkg = null;

  static const IconData female = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
