/// Flutter icons Socicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Socicon
///      fonts:
///       - asset: fonts/Socicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Socicon {
  Socicon._();

  static const _kFontFam = 'Socicon';
  static const _kFontPkg = null;

  static const IconData instagram = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData itunes = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData patreon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playstation = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sharethis = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stayfriends = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData identica = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsplash = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tiktok = IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
